# RegistroImplementacion.ps1
Set-StrictMode -Version Latest

function Iniciar-RegistroImplementacion {
    param([string]$DbPath,[string]$CorrelationId,[string]$NombreProyecto,[string]$Repositorio="",[string]$CommitSolicitado="",[string]$DeploymentId="")
    $DeploymentId = if ($DeploymentId) { $DeploymentId } else { [Guid]::NewGuid().ToString("N").Substring(0,12).ToUpper() }
    $Ahora = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
    $r = @{DbPath=$DbPath;Implementacion=@{correlation_id=$CorrelationId;nombre_proyecto=$NombreProyecto;repositorio=$Repositorio;commit_solicitado=$CommitSolicitado;commit_desplegado="";deployment_id=$DeploymentId;estado_general="EN_PROCESO";fecha_inicio=$Ahora;fecha_fin="";duracion_total_segundos=0;pasos_completados=0;pasos_fallidos=0;pasos_totales=13};Pasos=@()}
    $data = @((1,"SOLICITUD",@("01.01/nombre del proyecto","01.02/repositorio","01.03/parametros")),(2,"FACTORY",@("02.01/crear workspace","02.02/crear estructura","02.03/renderizar templates","02.04/validar placeholders","02.05/inicializar SQLite","02.06/registrar metadatos","02.07/inicializar Git")),(3,"GITHUB",@("03.01/crear repositorio","03.02/configurar repositorio","03.03/publicar codigo","03.04/verificar branch","03.05/verificar SHA")),(4,"CI CHILD",@("04.01/checkout","04.02/dependencias","04.03/validacion","04.04/resultado")),(5,"CONTROL PLANE",@("05.01/recibir parametros","05.02/validar identidad","05.03/checkout Child","05.04/validar infraestructura")),(6,"AUTENTICACION",@("06.01/GitHub OIDC","06.02/Azure login","06.03/comprobar resultado")),(7,"AZURE",@("07.01/localizar ASP-IAUR","07.02/comprobar reutilizacion","07.03/crear/reutilizar Web App","07.04/configurar runtime","07.05/configurar startup")),(8,"DEPLOY",@("08.01/construir ZIP","08.02/validar contenido ZIP","08.03/ZIP Deploy","08.04/reinicio","08.05/verificar SHA desplegado")),(9,"READINESS",@("09.01/comprobar disponibilidad","09.02/comprobar HTTP","09.03/comprobar health","09.04/comprobar identidad")),(10,"PRUEBAS FUNCIONALES",@("10.01","10.02/health","10.03/api/version","10.04/api/proyecto","10.05/openapi.json","10.06/swagger","10.07/redoc","10.08/endpoint 404")),(11,"EVIDENCIA",@("11.01/requested SHA","11.02/deployed SHA","11.03/OIDC","11.04/deployment","11.05/readiness","11.06/functional tests","11.07/identidad","11.08/infraestructura")),(12,"PUBLICACION",@("12.01/landing page","12.02/log de implementacion","12.03/accesos","12.04/estado final")),(13,"NAVEGADOR",@("13.01/abrir","13.02/abrir health","13.03/abrir version","13.04/abrir proyecto","13.05/abrir openapi","13.06/abrir swagger","13.07/abrir redoc")))
    foreach ($d in $data) {
        $num=$d[0];$nom=$d[1];$subs=$d[2]
        $paso=@{numero_paso=$num;nombre_paso=$nom;estado="PENDIENTE";fecha_inicio="";fecha_fin="";duracion_segundos=0;detalle="";evidencia="";resultado="";subpasos=@()}
        foreach($s in $subs){$parts=$s -split '/',2;if($parts.Count -ge 2){$paso.subpasos+=@{numero_subpaso=$parts[0];nombre_subpaso=$parts[1];estado="PENDIENTE";fecha_inicio="";fecha_fin="";duracion_segundos=0;detalle="";evidencia="";resultado=""}}else{$paso.subpasos+=@{numero_subpaso=$s;nombre_subpaso=$s;estado="PENDIENTE";fecha_inicio="";fecha_fin="";duracion_segundos=0;detalle="";evidencia="";resultado=""}}}
        $r.Pasos += $paso
    }
    Write-Host "[RI] Registry: $NombreProyecto"
    return $r
}
function Iniciar-PasoImplementacion { param($Registro,$NumeroPaso,$Detalle="") $p=$Registro.Pasos|Where-Object{$_.numero_paso -eq $NumeroPaso};if(-not$p){return};$a=(Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ");$p.estado="EN_PROCESO";$p.fecha_inicio=$a;$p.detalle=$Detalle }
function Finalizar-PasoImplementacion { param($Registro,$NumeroPaso,$Estado="COMPLETADO",$Detalle="",$Evidencia="",$Resultado="") $p=$Registro.Pasos|Where-Object{$_.numero_paso -eq $NumeroPaso};if(-not$p){return};$a=(Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ");$p.estado=$Estado;$p.fecha_fin=$a;if($Detalle){$p.detalle=$Detalle};if($Evidencia){$p.evidencia=$Evidencia};$p.resultado=if($Resultado){$Resultado}elseif($Estado-eq"COMPLETADO"){"PASS"}else{"FAIL"};if($p.fecha_inicio){try{$i=[datetime]::ParseExact($p.fecha_inicio.TrimEnd('Z'),"yyyy-MM-ddTHH:mm:ss",$null);$f=[datetime]::ParseExact($a.TrimEnd('Z'),"yyyy-MM-ddTHH:mm:ss",$null);$p.duracion_segundos=($f-$i).TotalSeconds}catch{$p.duracion_segundos=0}};if($Estado-eq"COMPLETADO"){$Registro.Implementacion.pasos_completados++}elseif($Estado-eq"FALLIDO"){$Registro.Implementacion.pasos_fallidos++} }
function Iniciar-SubpasoImplementacion { param($Registro,$NumeroPaso,$NumeroSubpaso,$Detalle="") $p=$Registro.Pasos|Where-Object{$_.numero_paso -eq $NumeroPaso};if(-not$p){return};$sp=$p.subpasos|Where-Object{$_.numero_subpaso -eq $NumeroSubpaso};if(-not$sp){return};$a=(Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ");$sp.estado="EN_PROCESO";$sp.fecha_inicio=$a;$sp.detalle=$Detalle }
function Finalizar-SubpasoImplementacion { param($Registro,$NumeroPaso,$NumeroSubpaso,$Estado="COMPLETADO",$Detalle="",$Evidencia="",$Resultado="") $p=$Registro.Pasos|Where-Object{$_.numero_paso -eq $NumeroPaso};if(-not$p){return};$sp=$p.subpasos|Where-Object{$_.numero_subpaso -eq $NumeroSubpaso};if(-not$sp){return};$a=(Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ");$sp.estado=$Estado;$sp.fecha_fin=$a;if($Detalle){$sp.detalle=$Detalle};if($Evidencia){$sp.evidencia=$Evidencia};$sp.resultado=if($Resultado){$Resultado}elseif($Estado-eq"COMPLETADO"){"PASS"}else{"FAIL"};if($sp.fecha_inicio){try{$i=[datetime]::ParseExact($sp.fecha_inicio.TrimEnd('Z'),"yyyy-MM-ddTHH:mm:ss",$null);$f=[datetime]::ParseExact($a.TrimEnd('Z'),"yyyy-MM-ddTHH:mm:ss",$null);$sp.duracion_segundos=($f-$i).TotalSeconds}catch{$sp.duracion_segundos=0}} }
function Finalizar-RegistroImplementacion { param($Registro,$Estado="COMPLETADO",$Detalle="") $a=(Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ");$Registro.Implementacion.fecha_fin=$a;$Registro.Implementacion.estado_general=$Estado;if($Registro.Implementacion.fecha_inicio){try{$i=[datetime]::ParseExact($Registro.Implementacion.fecha_inicio.TrimEnd('Z'),"yyyy-MM-ddTHH:mm:ss",$null);$f=[datetime]::ParseExact($a.TrimEnd('Z'),"yyyy-MM-ddTHH:mm:ss",$null);$Registro.Implementacion.duracion_total_segundos=($f-$i).TotalSeconds}catch{}};if($Detalle){$Registro.Implementacion.detalle_final=$Detalle} }
function Persistir-RegistroImplementacion { param($Registro) $db=$Registro.DbPath;$i=$Registro.Implementacion;$c=$i.correlation_id;if(-not(Test-Path $db)){Write-Warning "[RI] DB: $db";return $false};function e($v){return ($v -replace "'", "''")};$q1="INSERT INTO Implementacion (CorrelationId,NombreProyecto,Repositorio,CommitSolicitado,CommitDesplegado,DeploymentId,EstadoGeneral,PasosCompletados,PasosFallidos,PasosTotales,DuracionTotalSegundos,FechaInicio,FechaFin) VALUES ('$(e $c)','$(e $i.nombre_proyecto)','$(e $i.repositorio)','$(e $i.commit_solicitado)','$(e $i.commit_desplegado)','$(e $i.deployment_id)','$(e $i.estado_general)',$($i.pasos_completados),$($i.pasos_fallidos),$($i.pasos_totales),$($i.duracion_total_segundos),'$(e $i.fecha_inicio)','$(e $i.fecha_fin)') ON CONFLICT(CorrelationId) DO UPDATE SET EstadoGeneral=excluded.EstadoGeneral,PasosCompletados=excluded.PasosCompletados,PasosFallidos=excluded.PasosFallidos,DuracionTotalSegundos=excluded.DuracionTotalSegundos,FechaFin=excluded.FechaFin,CommitDesplegado=CASE WHEN excluded.CommitDesplegado!='' THEN excluded.CommitDesplegado ELSE CommitDesplegado END";sqlite3 $db $q1 2>&1|Out-Null;sqlite3 $db "DELETE FROM PasoImplementacion WHERE CorrelationId='$(e $c)';" 2>&1|Out-Null;foreach($p in $Registro.Pasos){$sj=$p.subpasos|ConvertTo-Json -Compress -Depth 3;$sj=$sj -replace "'", "''";$q2="INSERT INTO PasoImplementacion (CorrelationId,NumeroPaso,NombrePaso,NumeroSubpaso,NombreSubpaso,Estado,FechaInicio,FechaFin,DuracionSegundos,Detalle,Evidencia,Resultado) VALUES ('$(e $c)',$($p.numero_paso),'$(e $p.nombre_paso)','','','$(e $p.estado)','$(e $p.fecha_inicio)','$(e $p.fecha_fin)',$($p.duracion_segundos),'$(e $sj)','$(e $p.evidencia)','$(e $p.resultado)')";sqlite3 $db $q2 2>&1|Out-Null};Write-Host "[RI] Persisted";return $true}
Export-ModuleMember -Function Iniciar-RegistroImplementacion,Iniciar-PasoImplementacion,Finalizar-PasoImplementacion,Iniciar-SubpasoImplementacion,Finalizar-SubpasoImplementacion,Finalizar-RegistroImplementacion,Persistir-RegistroImplementacion